### ISSUE TITLE
Arm architecture is not supported in eu-west-3 region

### ISSUE THREAD

**Issue by SoulKyu** [reply-fr/sustainable-personal-accounts#53]
Make deploy will fail if you configure to deploy on eu-west-3 due to arm64 no't available yet.

```txt
 ❌ Deployment failed: Error: Stack Deployments Failed: Error: The stack named SpaCommitted failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "Architecture "arm64" is not supported in eu-west-3. Please select "x86_64" or remove the Architectures value from your request and try again (Service: Lambda, Status Code: 400, Request ID: 86cc75f7-53e7-481c-b049-7f464154bdd8)" (RequestToken: c8b878fb-3909-4930-05cb-2f6b01d54543, HandlerErrorCode: InvalidRequest), Resource handler returned message: "Architecture "arm64" is not supported in eu-west-3. Please select "x86_64" or remove the Architectures value from your request and try again (Service: Lambda, Status Code: 400, Request ID: a0e085ba-c4c7-41cf-a058-17ef5f3f99f0)" (RequestToken: 6b221b58-2201-02de-8377-f3dc062d7b5b, HandlerErrorCode: InvalidRequest), Resource handler returned message: "Architecture "arm64" is not supported in eu-west-3. Please select "x86_64" or remove the Architectures value from your request and try again (Service: Lambda, Status Code: 400, Request ID: 4ffd6aff-3192-4abc-8510-bf5fbddef80e)" (RequestToken: d31c3eb6-ed6f-8098-97da-0fa70f2bb833, HandlerErrorCode: InvalidRequest), Resource handler returned message: "Architecture "arm64" is not supported in eu-west-3. Please select "x86_64" or remove the Architectures value from your request and try again (Service: Lambda, Status Code: 400, Request ID: 43986f59-f13c-4b92-81e7-1ca615fce04d)" (RequestToken: f7fd9bb9-9b3e-72a4-e687-e7b9cffcbb7b, HandlerErrorCode: InvalidRequest), Resource handler returned message: "Architecture "arm64" is not supported in eu-west-3. Please select "x86_64" or remove the Architectures value from your request and try again (Service: Lambda, Status Code: 400, Request ID: 56180a28-09d3-48de-b2d9-38ff471a8da1)" (RequestToken: 3c159c43-bfc9-5a35-62b8-217a119c6e36, HandlerErrorCode: InvalidRequest)
    at deployStacks (/usr/lib/node_modules/aws-cdk/lib/deploy.ts:61:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at CdkToolkit.deploy (/usr/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:314:7)
    at initCommandLine (/usr/lib/node_modules/aws-cdk/lib/cli.ts:357:12)
```

**Comment by bernard357** [comment]
Codebuild projects have been set to x86 again in ce0db417eae9e7a37a5c54d29a14709735c2f118

**Comment by bernard357** [comment]
ARM architecture for lambda functions deployed by SPA is now an optional settings, as per fd28e826ac9fe5400c72962f9102c57c4955a342
